### ISSUE TITLE
Add unbreakable space before punctuation characters

### ISSUE THREAD

**Issue by bmarty** [NijiDigital/poesie#2]
As a user of poeditor script, I want to pass a parameter "--punctuation" to the script for it to add unbreakable space before any punctuation characters who need it.

Examples:
- "date:" => "date\u00A0:"
- "date :" => "date\u00A0:"
- ":" => ":"
- "\&gt;" => "\&gt;"

Acceptance criteria:
- All characteres ":", ";", "!", "?" will be preceded by "\u00A0" for Android. Any other space before those char are removed.
- ";" is not modified if it is used as termination char for html escaped sctring (ex: "\&gt;")

**Comment by AliSoftware** [comment]
Nice idea, but there's a glitch :wink:

> All characteres ":", ";", "!", "?" will be preceded by "\u00A0" for Android. Any other space before those char are removed.

This is problematic, because this rule isn't following the english typography. This rule only applies to some languages, like French, where the typography dictates that punctuation must have non-breaking spaces before. But English typography dictates that punctuation must not have any space beforehand.


What we could imagine instead is to only replace any space preceding a punctuation with non-breaking space (`"date :"` => `"date\u00A0:"`). But it would be an error to _add_ a nbsp if there isn't a space in the first place.

**Comment by bmarty** [comment]
Ok
